export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS" as const;
export const FETCH_CITY_ERROR = "FETCH_CITY_ERROR" as const;
export const FETCH_STATIC_CITIES_SUCCESS =
  "FETCH_STATIC_CITIES_SUCCESS" as const;
export const FETCH_STATIC_CITIES_ERROR = "FETCH_STATIC_CITIES_ERROR" as const;
