export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS' as const;
export const FETCH_CITY_ERROR = 'FETCH_CITY_ERROR' as const;
export const ADD_COMPARE_CITIES_SUCCESS = 'ADD_COMPARE_CITIES_SUCCESS' as const;
export const ADD_COMPARE_CITIES_ERROR = 'ADD_COMPARE_CITIES_ERROR' as const;
